language: node_js
node_js:
  - "8"
  
before_install:
    - npm install -g @angular/cli
install: npm install

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: "ejZX0EBpM2upuro2jqUFieLT33zaicdREZXqD+b6VSnbmjFo8sj4gBJvIlRIWrw4G2eDkVr7dK5zytGDlEbAmDyMTD3P2q1tQYgkdkcMtZbMruh9t0kEJP+6KsUrzK/mwLlvIDVId/Kyi1Vf3V0aO1P8gChxck06QVmslmUHljlhJEZFetnMEmRvMJbdR9CyKBq4DzNQnFcTwpIMyiFghssbdjJ1obE+NqdfnchgccEOOaq5URy88tf1XtBGLLPgyyS5qmaaid6nxGiS4bOfP9VMyQ/KftvUHU/cl68K3bxwQm6oOAXRtMQslqSkfTJzwBapFM5h0cknGHUsfZOh6Sn3nsG4PYB2+nh5SoxDEO9glDZi6IlbXdDAEomoQtMCY0AGzwgc1YUWcdHjj414RGRT0lEvK0Qz+NgvdYSJPpqqwzt07uOrha70OgPj5cjqs1qnS8vInjK76Y0DfmUoixyiFSb0E03cpxc3f5qBbjZqY43ATst4WxhFC7RoI7z0B0RXZ/c/mKHPMwk0+B/RY6H/DPlYqvCJyQz3C3vQ1LpGzfabfz1Tte6AUNTMaOsqVXAsymormXJeUFbt5hXOBR4+TABCMAcAatjD4BcPApyegAL2tO/q1wN5Rj9BVMw/UH/k5XwXohEYlwXZEsMpBiqN2DH6V6N6NI39HpUgYTE="
  app: abcontrol-spring-boot-web-full
  on:
    repo: savannadenega/abcontrol-spring-boot-web-full